<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FFXIVConfigManager.Domain\FFXIVConfigManager.Domain.csproj" />
    <ProjectReference Include="..\FFXIVConfigManager.Application\FFXIVConfigManager.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
